site_name: The Art of Machine Learning
# site_url: https://james-willett.github.io/mkdocs-material-youtube-tutorial/
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime

plugins:
  - search
  - bibtex:
      bib_file: "reference.bib"

markdown_extensions:
  - footnotes
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
# nav:
#   - Home: index.md
#   - NLP: 
#     - natural-language-processing/foundations.md


# plugins:
  # - social

# extra:
  # social:
  #   - icon: fontawesome/brands/github-alt
  #     link: https://github.com/james-willett
  #   - icon: fontawesome/brands/twitter
  #     link: https://twitter.com/TheJamesWillett
  #   - icon: fontawesome/brands/linkedin
  #     link: https://www.linkedin.com/in/willettjames/

# markdown_extensions:
#   - pymdownx.highlight:
#       anchor_linenums: true
#   - pymdownx.inlinehilite
#   - pymdownx.snippets
#   - admonition
#   - pymdownx.arithmatex:
#       generic: true
#   - footnotes
#   - pymdownx.details
#   - pymdownx.superfences
#   - pymdownx.mark
#   - attr_list
#   - pymdownx.emoji:
#       emoji_index: !!python/name:materialx.emoji.twemoji
#       emoji_generator: !!python/name:materialx.emoji.to_svg

#copyright: |
#  &copy; 2023 <a href="https://github.com/james-willett"  target="_blank" rel="noopener">James Willett</a>